/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbank;


import java.util.LinkedList;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.lang.reflect.Type;
/**
 *
 * @author Mina
 */ 
public class MakeADonationWindow extends javax.swing.JFrame {
    Donor d ;

    /**
     * Creates new form MakeADonationWindow
     */
    public MakeADonationWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DonorsNameLabel = new javax.swing.JLabel();
        DonorsNameTextField = new javax.swing.JTextField();
        ShowDonorInformationButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DonorInformationTextArea = new javax.swing.JTextArea();
        PhoneNumberTextField = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        DonateButton = new javax.swing.JButton();
        InfectedCheckBox = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DonorsNameLabel.setText("Donor's Name");

        DonorsNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorsNameTextFieldActionPerformed(evt);
            }
        });

        ShowDonorInformationButton.setText("Show Donor's Information");
        ShowDonorInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDonorInformationButtonActionPerformed(evt);
            }
        });

        DonorInformationTextArea.setEditable(false);
        DonorInformationTextArea.setColumns(20);
        DonorInformationTextArea.setRows(5);
        jScrollPane1.setViewportView(DonorInformationTextArea);

        PhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextFieldActionPerformed(evt);
            }
        });

        PhoneNumberLabel.setText("Phone Number");

        DonateButton.setText("Donate");
        DonateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonateButtonActionPerformed(evt);
            }
        });

        InfectedCheckBox.setLabel("Infected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DonorsNameLabel)
                                    .addComponent(PhoneNumberLabel))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DonorsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(ShowDonorInformationButton)))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfectedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DonateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonorsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonorsNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PhoneNumberLabel))
                .addGap(17, 17, 17)
                .addComponent(ShowDonorInformationButton)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(InfectedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(DonateButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DonorsNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorsNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonorsNameTextFieldActionPerformed

    private void ShowDonorInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDonorInformationButtonActionPerformed
        while(true)
        {
            String PhoneNumber;
            while(true)
            {
                try{
                    PhoneNumber = PhoneNumberTextField.getText();
                    break;
                }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please re-enter the PhoneNumber ");
            System.out.println(e.toString());
        }
            }
            try{
                System.out.println("bey5ali el pointer d yeshawer 3ala el donor eli bene3melo show info");
                d = ClientDataBase.search_Donor(PhoneNumber);
                if(d.Name.equals("null"))
                    JOptionPane.showMessageDialog(null, "This Donor is not registered yet");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "This Donor is not registered yet");
                this.dispose();
                Window w = new Window();
                w.setVisible(true);
                return ;
            }
            
            
            
            DonorInformationTextArea.setText("Name : "+d.Name+"\nBlood Type : "+d.BloodType
            +"\nLast Donation was in : "+d.Last_donate);
            
            Date currentDay = Calendar.getInstance().getTime();
            //Allowed.setMonth((d.Last_donate.getMonth()-1+3)%12+1);
            int day=0;
            int month =-1; 
            int year =-1;
            int CurrentMonth=0;
            try{
                System.out.println(d.Last_donate.getDate()+" THIS IS THE DAY d.lastdonate.getDay()");
                        
                // ya3ni law el donor lam yatabara3 abl kda hay5osh fel catch
                 day = d.Last_donate.getDate();
                 //d.Last_donate=currentDay;
                 CurrentMonth = d.Last_donate.getMonth();
            }
            catch(Exception e)
            {
                System.out.println(e.toString());
                JOptionPane.showMessageDialog(null, "The donor has never donated before");
                System.out.println("el YOM HOWA"+day);
                canDonate=true;
                return;
                
            }
            
            
            if(d.Last_donate.getMonth()>=10)
            {
                year = d.Last_donate.getYear()+1;
                if(d.Last_donate.getMonth()==10)
                    month =1 ;
                else if(d.Last_donate.getMonth()==11)
                    month = 2 ; 
                else if(d.Last_donate.getMonth()==12)
                    month =3 ;
            }
            else
            {
                month=d.Last_donate.getMonth()+3;
                
            }
            System.out.println("year "+year+"month "+month +"day "+day);
            
            Date Allowed= new Date(year , month , day);
            
            System.out.println("hay5osh el if condition");
            if(currentDay.before(Allowed)&&currentDay!=null)
            {
                System.out.println("da5al fel if condition");
                JOptionPane.showMessageDialog(null, "this Donor Cannot donate");
            }
            else if(d.Last_donate==null||currentDay.after(Allowed))
            {
                System.out.println("da5al fel else if condition");
                canDonate=true;
                 JOptionPane.showMessageDialog(null, "The Donor Can donate another Time beginning from:\n"+
                         Allowed.toString()+"\nIf you want to Donate please click on the Donate button bellow");
                // Blood b = new Blood
                
                            
            }
            break;
            
            
        
            
            
        
        }
        
        
    
        
        

    
    }//GEN-LAST:event_ShowDonorInformationButtonActionPerformed

    private void PhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextFieldActionPerformed

    private void DonateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonateButtonActionPerformed
            if(canDonate==false)
            {
                 JOptionPane.showMessageDialog(null, "Please check if the Donor is Allowed to donate");
            }
            else 
            {
                System.out.println(d.BloodType);
                if(d.BloodType.equals("Blood A"))
                {
                    System.out.println("da5al gowa el save beta3 bloodA");
                    BloodStock.blood_A.add(new BloodA(Calendar.getInstance().getTime(), InfectedCheckBox.getState()));
                    BloodStock.saveListToFile(BloodStock.blood_A, "BloodA");
                }
                else if(d.BloodType.equals("Blood B"))
                {
                    System.out.println("da5al gowa el save beta3 bloodB");
                    BloodStock.blood_B.add(new BloodB(Calendar.getInstance().getTime(), InfectedCheckBox.getState()));
                    BloodStock.saveListToFile(BloodStock.blood_B, "BloodB");
                }
                else
                {
                    System.out.println("da5al gowa el save beta3 bloodO");
                    BloodStock.blood_O.add(new BloodO(Calendar.getInstance().getTime(), InfectedCheckBox.getState()));
                    BloodStock.saveListToFile(BloodStock.blood_O, "BloodO");
                }
                String phoneNumber =PhoneNumberTextField.getText();
            int index =ClientDataBase.GetDonorIndex(phoneNumber);
            ClientDataBase.Donors_list.get(index).Last_donate=Calendar.getInstance().getTime();
            ClientDataBase.saveList(ClientDataBase.Donors_list , "Donor");
            JOptionPane.showMessageDialog(null, "Donation was successful , Thank you for caring about the patient who need Blood , we Love you , ma3 ta7eyat mina w toni w david");
            this.dispose();
            Window w = new Window();
            w.setVisible(true);
                
            }
            
    }//GEN-LAST:event_DonateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    boolean canDonate=false;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeADonationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeADonationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeADonationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeADonationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeADonationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DonateButton;
    private javax.swing.JTextArea DonorInformationTextArea;
    private javax.swing.JLabel DonorsNameLabel;
    private javax.swing.JTextField DonorsNameTextField;
    private java.awt.Checkbox InfectedCheckBox;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JButton ShowDonorInformationButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
